"""Markdown report generator formatted for GitHub, Bug-Bounty notes, and documentation."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from vulnforge import __version__
from vulnforge.scanners.result import Finding, FindingSeverity
from vulnforge.utils.redaction import redact_secrets


def generate_markdown_report(
    scan_data: Dict[str, Any],
    findings: List[Finding],
    endpoints: Optional[List[Any]] = None,
    technologies: Optional[List[Any]] = None,
    statistics: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate GitHub-compatible Markdown security assessment report.

    Args:
        scan_data: Scan session metadata.
        findings: List of Finding models.
        endpoints: Discovered endpoint inventory.
        technologies: Detected technology stack.
        statistics: Scan execution statistics.

    Returns:
        Markdown document string.
    """
    target = scan_data.get("target", {})
    target_url = target.get("raw_url") if isinstance(target, dict) else scan_data.get("target_url", "Target")
    scan_id = scan_data.get("scan_id") or scan_data.get("id", "N/A")
    profile = scan_data.get("profile", "safe")
    stats = statistics or scan_data.get("statistics", {})

    # Severity counts
    sev_counts = {
        FindingSeverity.CRITICAL: 0,
        FindingSeverity.HIGH: 0,
        FindingSeverity.MEDIUM: 0,
        FindingSeverity.LOW: 0,
        FindingSeverity.INFO: 0,
    }
    for f in findings:
        sev = f.severity if isinstance(f.severity, FindingSeverity) else FindingSeverity(str(f.severity).upper())
        sev_counts[sev] = sev_counts.get(sev, 0) + 1

    lines: List[str] = [
        f"# VulnForge Security Assessment Report — {target_url}",
        "",
        f"> **Generated by VulnForge v{__version__}** | Scan ID: `{scan_id}` | Date: `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}` | Profile: `{profile.upper()}`",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        "",
        f"A web application security assessment was conducted on target `{target_url}` using VulnForge's non-destructive reconnaissance and finding correlation engine. A total of **{len(findings)}** security findings were identified.",
        "",
        "| Severity | Count |",
        "| :--- | :--- |",
        f"| **CRITICAL** | `{sev_counts[FindingSeverity.CRITICAL]}` |",
        f"| **HIGH** | `{sev_counts[FindingSeverity.HIGH]}` |",
        f"| **MEDIUM** | `{sev_counts[FindingSeverity.MEDIUM]}` |",
        f"| **LOW** | `{sev_counts[FindingSeverity.LOW]}` |",
        f"| **INFO** | `{sev_counts[FindingSeverity.INFO]}` |",
        "",
        "---",
        "",
        "## 2. Scan Statistics & Scope",
        "",
        f"- **Target URL**: `{target_url}`",
        f"- **Requests Sent**: `{stats.get('requests_sent', 0)}`",
        f"- **Successful Responses (2xx)**: `{stats.get('requests_successful', 0)}`",
        f"- **Discovered Endpoints**: `{len(endpoints) if endpoints else stats.get('endpoints_count', 0)}`",
        f"- **Execution Duration**: `{stats.get('duration_seconds', 0.0):.1f}s`",
        "",
    ]

    # Technologies
    if technologies:
        lines.extend([
            "---",
            "",
            "## 3. Technology Fingerprints",
            "",
            "| Technology | Category | Version | Confidence |",
            "| :--- | :--- | :--- | :--- |",
        ])
        for t in technologies:
            lines.append(f"| **{t.get('name', '')}** | {t.get('category', '')} | {t.get('version') or '-'} | {t.get('confidence', 0)}% |")
        lines.append("")

    # Detailed findings
    lines.extend([
        "---",
        "",
        f"## 4. Detailed Security Findings ({len(findings)})",
        "",
    ])

    if not findings:
        lines.append("_No vulnerabilities or security misconfigurations were identified during this assessment._\n")
    else:
        for idx, f in enumerate(findings, 1):
            sev_str = f.severity.value if hasattr(f.severity, "value") else str(f.severity)
            status_str = f.status.value if hasattr(f.status, "value") else str(f.status)
            evidence_str = redact_secrets(f.evidence) if f.evidence else "No specific raw evidence captured."
            curl_cmd = f"curl -i -s -k '{f.endpoint_url}'"

            lines.extend([
                f"### {idx}. [{sev_str}] {f.title}",
                "",
                f"- **Severity**: `{sev_str}`",
                f"- **Confidence**: `{f.confidence}%` ({status_str})",
                f"- **Category**: `{f.category}`",
                f"- **Endpoint**: `{f.endpoint_url}`",
                f"- **Parameter**: `{f.parameter_name or 'N/A'}`",
                f"- **Scanner**: `{f.scanner}`",
                "",
                "#### Description",
                f"{f.description}",
                "",
                "#### Supporting Evidence",
                "```http",
                evidence_str,
                "```",
                "",
                "#### Reproduction",
                "```bash",
                curl_cmd,
                "```",
                "",
                "#### Remediation",
                f"{f.recommendation}",
                "",
            ])

            if f.references:
                lines.append("#### References")
                for r in f.references:
                    lines.append(f"- [{r}]({r})")
                lines.append("")

            lines.append("---")
            lines.append("")

    return "\n".join(lines)
